<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<title>Faça seu login</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<style>
		body{
			padding-top: 40px;
			padding-bottom: 40px
			background-color: #eee;
		}
		.form-signin{
			max-width: 330px;
			padding: 15px;
			margin: 0 auto;
		}
		.form-signin .form-signin-heading,
		.form-signin .checkbox{
			margin-bottom: 10px;
		}
		.form-signin .checkbox{
			font-weight: normal;
		}
		.form-signin .form-control{
			position: relative;
			height: auto;
			-webkit-box-sizing: border-box;
			-moz-box-sizing: border-box;
			box-sizing: border-box;
			padding: 10px;
			font-size: 16px;
		}
		.form-signin .form-control:focus{
			z-index: 2;
		}
		.form-signin input[type="email"]{
			margin-bottom: -1px;
			border-top-left-radius: 0;
			border-top-right-radius: 0;
		}
		.form-signin input[type="password"]{
			margin-bottom: 10px;
			border-top-left-radius: 0;
			border-top-right-radius: 0;
		}

	</style>

</head>
<body>
	<div class="container"> 
		<?php if(isset($erro)):?>
			<div class="alert alert-danger"><?= isset($erro) ? $erro : '' ?></div>
		<?php endif; ?>
		<form class="form-signin" action = "<?= PATH ?>/admin/login" method="post">
			<h2 class="form-signin-heading">Faça seu login</h2>
			<label for="inputEmail" class="sr-only" >Endereço de email</label>
			<input type="email" id="inputEmail" class="form-control" placeholder="Endereço de email" name="email" require>
			<label for="inputPassword" class="sr-only" >Senha</label>
			<input type="password" id="inputPassword" class="form-control" placeholder="Senha" name="senha" equire>
			<div class="checkbox">
				<label>
					<input type="checkbox" valeu="remember-me" >Lembre-me
				</label>
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>


		</form>

	</div>
</body>
</html>