<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8 ">
	<title><?= isset($title) ? $title : 'Área Administrativa' ?></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
  <div class="container">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent" >
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<?= PATH ?>/admin/posts" alt = "posts">Posts</a>
      </li>
     
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li class="nav-item"><a class="nav-link" href="<?= PATH ?>/admin/logout">&raquo; Sair</a></li>
    </ul>
  </div>
</div>
</nav>