<div class="container">
	

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h2>Novo Post</h2>
			<?php  if(isset($error)):?>
				<div class="alert alert-danger"><?= $error ?></div>
			<?php endif; ?>
			<div class="panel panel-default">
				<div class="panel-heading">
					Formulário de cadastro de post
				</div>	
				<div class="panel-body">
					<form action="<?= PATH ?>/admin/posts/add" method="post">
						<div class="form-group">
							<label for="titulo">Título</label>
							<input type="text" class="form-control" name="titulo" id="titulo" placeholder="título">
						</div>
						<div class="form-group">
							<label for="descricao">Descrição</label>
							<textarea class="form-control" name="descricao" id="descricao" cols="30" rows="10"></textarea>
						</div>

						<button type="submit" class="btn btn-default">Cadastrar</button>
					</form>	
				</div>		
			</div>
		</div>
	</div>
</div>