</!DOCTYPE html>

<html lang="pt-br">
<head>
	<meta charset="utf-8"> 
	<title>Projeto Slim Framework</title>
	<link rel="stylesheet" type="text/css" href="<?= PATH ?>/public/css/estilo.css">
</head>
<body>
	<header>
		<div class="container">
			<h1 class="logo-site">Logo site</h1>
			<nav id="menu">
				<ul>
					<li><a href="<?= PATH ?>" alt="home">Home</a></li>
						<li><a href="<?= PATH ?>/sobre" alt="sobre">Sobre</a></li>
						<li><a href="<?= PATH ?>/contato" alt="contato">Contato</a></li>
				</ul>
			</nav>
		</div>
	</header>
	<section>
		<div class="container">